# Generated by Django 3.0.5 on 2020-04-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0002_auto_20200410_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='details',
            field=models.CharField(max_length=1000),
        ),
    ]
