# Generated by Django 3.0.5 on 2020-04-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0003_auto_20200410_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='agile.Category'),
        ),
    ]
